# Generated by Django 4.2.6 on 2023-10-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClimbingArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(help_text='Enter field documentation', max_length=20)),
                ('type_of_climbing', models.CharField(choices=[('B', 'Bouldering'), ('S', 'Sport'), ('T', 'Traditional')], default='B', max_length=20)),
                ('rock_type', models.CharField(choices=[('Gran', 'Granite'), ('Sand', 'Sand'), ('Lime', 'Limestone'), ('Quartz', 'Quartzite')], default='Gran', max_length=20)),
            ],
            options={
                'ordering': ['area_name'],
            },
        ),
    ]
