# Generated by Django 4.2.6 on 2023-10-06 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climbingMap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a Rock Type', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='climbingarea',
            name='description',
            field=models.TextField(default='', help_text='Enter a description of the climbing area', max_length=2000),
        ),
        migrations.AlterField(
            model_name='climbingarea',
            name='rock_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='climbingMap.rocktype'),
        ),
    ]
