# Generated by Django 4.2.6 on 2023-10-07 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climbingMap', '0002_rocktype_climbingarea_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rocktype',
            options={'ordering': ['name']},
        ),
    ]
