# Generated by Django 4.2.6 on 2023-10-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbingMap', '0003_alter_rocktype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbingarea',
            name='type_of_climbing',
            field=models.CharField(choices=[('Bouldering', 'Bouldering'), ('Sport', 'Sport'), ('Trad', 'Traditional'), ('Muli-Pitch', 'Multi-Pitch')], default='Bouldering', max_length=20),
        ),
    ]
